import React, { createContext, useContext, useEffect, useState } from "react";

const STRINGS = {
    es: {
        app_name: "soyapostol",
        tagline: "",
        nav: {
            dashboard: "Inicio",
            readings: "Lecturas",
            liturgy: "Liturgia de las Horas",
            prayers: "Oraciones",
            rosary: "Santo Rosario",
            examen: "Examen de Conciencia",
            news: "Noticias",
            bible: "Biblia",
            catechism: "Catecismo",
            favorites: "Favoritos",
            login: "Entrar",
            register: "Crear cuenta",
            logout: "Salir",
            more: "Más",
        },
        common: {
            loading: "Cargando…",
            error: "Error",
            today: "Hoy",
            source: "Fuente",
            save_favorite: "Guardar en favoritos",
            saved: "Guardado",
            remove: "Quitar",
            email: "Correo electrónico",
            password: "Contraseña",
            name: "Nombre",
            sign_in: "Iniciar sesión",
            create_account: "Crear cuenta",
            no_account: "¿No tienes cuenta?",
            have_account: "¿Ya tienes cuenta?",
            welcome_back: "Bienvenido de nuevo",
            join_apostol: "Únete a Apostol",
            select: "Seleccionar",
            view: "Ver",
            search: "Buscar",
            refresh: "Actualizar",
            back_to_menu: "Volver al menú",
            back_to_top: "Volver arriba",
        },
        sections: {
            readings_desc: "Las lecturas del día con comentario del Evangelio",
            liturgy_desc: "Oración litúrgica de las Horas",
            prayers_desc: "Compendio de oraciones católicas",
            rosary_desc: "Reza el Santo Rosario, día por día",
            examen_desc: "Recursos para tu examen de conciencia",
            news_desc: "EWTN, ACI Prensa y Vatican News",
            bible_desc: "La Sagrada Biblia católica completa",
            catechism_desc: "Catecismo de la Iglesia Católica",
            favorites_desc: "Tus textos guardados",
        },
        readings: {
            first: "Primera Lectura",
            psalm: "Salmo",
            second: "Segunda Lectura",
            gospel: "Evangelio",
            commentary: "Comentario",
            reflection_eyebrow: "Comentario al Evangelio",
            reflection_title: "Reflexión del día",
            reflection_credit: "Comentario por gentileza de",
            eod_eyebrow: "Otra reflexión",
            eod_title: "Comentario de Evangelio del Día",
            eod_unavailable: "Comentario de Evangelio del Día no disponible por el momento.",
        },
        rosary: {
            title: "Santo Rosario",
            today_eyebrow: "Misterios de hoy",
            choose_eyebrow: "Misterios seleccionados",
            cover_subtitle: "Toma tu rosario, respira profundo y comienza con el corazón abierto a María.",
            begin: "Comenzar",
            change_mystery: "Cambiar misterio",
            previous: "Anterior",
            next: "Siguiente",
            restart: "Reiniciar",
            help: "Desliza, toca los lados o usa las flechas del teclado para avanzar.",
            mystery_n: "{n}.º Misterio",
            decade_n: "Decena {n}",
            intro_three_eyebrow: "Tres Avemarías",
            prayer_label: "Oración",
            bead_progress: "{n} de {total}",
            tap_bead: "Tocar para contar",
            decade_done: "Decena completa",
            reset: "Reiniciar contador",
            completed_eyebrow: "Bien hecho",
            completed_title: "Has completado el Santo Rosario",
            completed_subtitle: "Que la Virgen María te acompañe hoy y siempre.",
            pray_again: "Rezar de nuevo",
        },
        examen: { upload: "Subir documento", title: "Título", description: "Descripción", file: "Archivo", admin_only: "Solo el administrador puede subir documentos.", empty: "Aún no hay documentos." },
        catechism: {
            search_placeholder: "Buscar por número (ej. 144) o por texto…",
            results_count: "{count} resultado(s)",
            total_count: "{count} párrafos",
            no_results: "Sin resultados. Prueba otro término o número.",
            load_more: "Cargar más",
        },
        bible: {
            search_placeholder: "Buscar palabra clave o referencia (ej. \"Juan 3:16\"). Pulsa Enter para saltar.",
            results_count: "{count} resultado(s)",
            no_results: "Sin resultados. Prueba otra palabra o referencia.",
            go_to: "Ir a",
        },
        admin: {
            eyebrow: "Panel de administrador",
            new_prayer: "Nueva oración",
            edit_prayer: "Editar oración",
            db_hint: "Las oraciones se guardan en la base de datos. Tus cambios persisten para todos los usuarios.",
            title: "Título",
            category: "Categoría",
            choose_category: "Elige una categoría…",
            new_category: "+ Nueva categoría",
            new_category_name: "Nombre de la nueva categoría",
            content: "Texto de la oración",
            content_placeholder: "Pega aquí el texto. Una línea en blanco separa párrafos.",
            add: "Añadir oración",
            save: "Guardar cambios",
            cancel: "Cancelar",
            edit: "Editar",
            delete: "Eliminar",
            stored_count: "{count} oraciones",
            empty: "Aún no hay oraciones.",
            no_filter_matches: "Sin resultados para ese filtro.",
            filter_placeholder: "Filtrar por título o categoría…",
            imported_badge: "Importada",
            created: "Oración añadida",
            updated: "Oración actualizada",
            deleted: "Oración eliminada",
            confirm_delete: "¿Eliminar «{title}»?",
            missing_fields: "Completa título, categoría y texto.",
        },
        auth: {
            forgot_password: "¿Olvidaste tu contraseña?",
            recover_eyebrow: "Recuperar acceso",
            forgot_password_intro: "Te enviaremos un enlace para restablecer tu contraseña. Caduca en 60 minutos.",
            send_reset_link: "Enviar enlace",
            reset_link_issued: "Enlace de recuperación creado",
            reset_link_demo_hint: "Modo demo: copia el enlace que aparece abajo para continuar.",
            reset_link_sent_generic: "Si el correo existe, te enviamos un enlace de recuperación.",
            demo_link_label: "Tu enlace (modo demo)",
            demo_link_help: "Copia y pégalo en una nueva pestaña, o ábrelo abajo. En producción este enlace llegaría por email.",
            copy: "Copiar",
            link_copied: "Enlace copiado",
            open_reset_page: "Abrir página de restablecimiento",
            reset_password: "Nueva contraseña",
            new_password: "Nueva contraseña",
            confirm_password: "Confirmar contraseña",
            update_password: "Actualizar contraseña",
            password_updated: "Contraseña actualizada. Ya puedes iniciar sesión.",
            password_too_short: "La contraseña debe tener al menos 8 caracteres.",
            passwords_mismatch: "Las contraseñas no coinciden.",
            reset_missing_token: "Falta el token de recuperación. Solicita un enlace nuevo.",
        },
    },
    en: {
        app_name: "soyapostol",
        tagline: "",
        nav: {
            dashboard: "Home",
            readings: "Readings",
            liturgy: "Liturgy of the Hours",
            prayers: "Prayers",
            rosary: "Holy Rosary",
            examen: "Examen of Conscience",
            news: "News",
            bible: "Bible",
            catechism: "Catechism",
            favorites: "Favorites",
            login: "Sign in",
            register: "Create account",
            logout: "Sign out",
            more: "More",
        },
        common: {
            loading: "Loading…",
            error: "Error",
            today: "Today",
            source: "Source",
            save_favorite: "Save to favorites",
            saved: "Saved",
            remove: "Remove",
            email: "Email",
            password: "Password",
            name: "Name",
            sign_in: "Sign in",
            create_account: "Create account",
            no_account: "Don't have an account?",
            have_account: "Already have an account?",
            welcome_back: "Welcome back",
            join_apostol: "Join Apostol",
            select: "Select",
            view: "View",
            search: "Search",
            refresh: "Refresh",
            back_to_menu: "Back to menu",
            back_to_top: "Back to top",
        },
        sections: {
            readings_desc: "Today's readings with Gospel commentary",
            liturgy_desc: "Liturgy of the Hours prayer",
            prayers_desc: "Compendium of Catholic prayers",
            rosary_desc: "Pray the Holy Rosary, day by day",
            examen_desc: "Resources for your examination of conscience",
            news_desc: "EWTN, ACI Prensa and Vatican News",
            bible_desc: "The complete Catholic Holy Bible",
            catechism_desc: "Catechism of the Catholic Church",
            favorites_desc: "Your saved passages",
        },
        readings: {
            first: "First Reading",
            psalm: "Psalm",
            second: "Second Reading",
            gospel: "Gospel",
            commentary: "Commentary",
            reflection_eyebrow: "Gospel commentary",
            reflection_title: "Daily reflection",
            reflection_credit: "Commentary courtesy of",
            eod_eyebrow: "Another reflection",
            eod_title: "Evangelio del Día commentary",
            eod_unavailable: "Evangelio del Día commentary is unavailable right now.",
        },
        rosary: {
            title: "Holy Rosary",
            today_eyebrow: "Today's Mysteries",
            choose_eyebrow: "Selected Mysteries",
            cover_subtitle: "Take your rosary, breathe deeply, and begin with a heart open to Mary.",
            begin: "Begin",
            change_mystery: "Change mystery",
            previous: "Previous",
            next: "Next",
            restart: "Restart",
            help: "Swipe, tap the sides, or use the keyboard arrows to navigate.",
            mystery_n: "Mystery {n}",
            decade_n: "Decade {n}",
            intro_three_eyebrow: "Three Hail Marys",
            prayer_label: "Prayer",
            bead_progress: "{n} of {total}",
            tap_bead: "Tap to count",
            decade_done: "Decade complete",
            reset: "Reset counter",
            completed_eyebrow: "Well done",
            completed_title: "You have completed the Holy Rosary",
            completed_subtitle: "May the Virgin Mary walk with you today and always.",
            pray_again: "Pray again",
        },
        examen: { upload: "Upload document", title: "Title", description: "Description", file: "File", admin_only: "Only the administrator can upload documents.", empty: "No documents yet." },
        catechism: {
            search_placeholder: "Search by number (e.g. 144) or text…",
            results_count: "{count} result(s)",
            total_count: "{count} paragraphs",
            no_results: "No results. Try another term or number.",
            load_more: "Load more",
        },
        bible: {
            search_placeholder: "Search keyword or reference (e.g. \"John 3:16\"). Press Enter to jump.",
            results_count: "{count} result(s)",
            no_results: "No results. Try another word or reference.",
            go_to: "Go to",
        },
        admin: {
            eyebrow: "Admin panel",
            new_prayer: "New prayer",
            edit_prayer: "Edit prayer",
            db_hint: "Prayers are stored in the database. Your changes persist for everyone.",
            title: "Title",
            category: "Category",
            choose_category: "Choose a category…",
            new_category: "+ New category",
            new_category_name: "New category name",
            content: "Prayer text",
            content_placeholder: "Paste the text here. A blank line separates paragraphs.",
            add: "Add prayer",
            save: "Save changes",
            cancel: "Cancel",
            edit: "Edit",
            delete: "Delete",
            stored_count: "{count} prayers",
            empty: "No prayers yet.",
            no_filter_matches: "No matches for that filter.",
            filter_placeholder: "Filter by title or category…",
            imported_badge: "Imported",
            created: "Prayer added",
            updated: "Prayer updated",
            deleted: "Prayer deleted",
            confirm_delete: "Delete \"{title}\"?",
            missing_fields: "Complete title, category and text.",
        },
        auth: {
            forgot_password: "Forgot your password?",
            recover_eyebrow: "Recover access",
            forgot_password_intro: "We'll send you a link to reset your password. It expires in 60 minutes.",
            send_reset_link: "Send reset link",
            reset_link_issued: "Reset link issued",
            reset_link_demo_hint: "Demo mode: copy the link shown below to continue.",
            reset_link_sent_generic: "If the email exists, we sent you a reset link.",
            demo_link_label: "Your link (demo mode)",
            demo_link_help: "Copy and paste it into a new tab, or open it below. In production this link would arrive by email.",
            copy: "Copy",
            link_copied: "Link copied",
            open_reset_page: "Open reset page",
            reset_password: "New password",
            new_password: "New password",
            confirm_password: "Confirm password",
            update_password: "Update password",
            password_updated: "Password updated. You can sign in now.",
            password_too_short: "Password must be at least 8 characters.",
            passwords_mismatch: "Passwords do not match.",
            reset_missing_token: "Reset token missing. Request a new link.",
        },
    },
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
    const [lang, setLang] = useState(() => localStorage.getItem("apostol_lang") || "es");
    useEffect(() => { localStorage.setItem("apostol_lang", lang); }, [lang]);

    const t = (path, vars) => {
        const parts = path.split(".");
        let v = STRINGS[lang];
        for (const p of parts) {
            if (v && Object.prototype.hasOwnProperty.call(v, p)) v = v[p];
            else return path;
        }
        if (typeof v === "string" && vars) {
            return v.replace(/\{(\w+)\}/g, (m, k) =>
                Object.prototype.hasOwnProperty.call(vars, k) ? String(vars[k]) : m);
        }
        return v;
    };
    return (
        <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>
    );
}

export const useLang = () => useContext(LangContext);
